### ISSUE TITLE
NPE in createHashParameters (docker only)

### ISSUE THREAD

**Issue by y-a-n-n** [SmartMoveSystems/keycloak-firebase-scrypt#1]
When running via docker-compose, attempting to create hash parameters entity throws a NullPointerException:

```
21:52:29,429 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-5) Uncaught server error: java.lang.NullPointerException
        at deployment.keycloak-firebase-scrypt-2.0.3.jar//com.smartmovesystems.keycloak.firebasescrypt.rest.ScryptHashParametersResource.createHashParameters(ScryptHashParametersResource.java:25)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.resteasy-jaxrs@3.12.1.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
```

**Comment by y-a-n-n** [comment]
Fixed by using manual deployment script for module rather than JBoss auto-deploy
